create table if not exists product (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY primary key,
    name varchar(255),
    description varchar(255),
    category varchar(255),
    creation_date TIMESTAMP,
    price double
    );

create table if not exists client(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY primary key,
    name varchar(255),
    last_name varchar(255),
    mobile varchar(255)
);

create table if not exists sale(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY primary key,
    creation_date TIMESTAMP,
    client INTEGER,
    seller varchar(255),
    total REAL
);

create table if not exists sale_product(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY primary key,
    sale int,
    product int,
    quantity int,
    price real
);


create table if not exists sale_transaction(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY primary key,
    action_type varchar(255),
    old_value JAVA_OBJECT,
    new_value JAVA_OBJECT,
    sale INTEGER,
    action_date TIMESTAMP
);